#!/bin/bash

################################################################################
# containerd 설정 스크립트
# Harbor 레지스트리를 사용하기 위한 containerd 설정 자동화
################################################################################

set -e

# 색상 정의
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

log_info() {
    echo -e "${GREEN}[INFO]${NC} $1"
}

log_warn() {
    echo -e "${YELLOW}[WARN]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# Root 권한 확인
if [ "$(id -u)" -ne 0 ]; then
    log_error "이 스크립트는 root 권한이 필요합니다."
    echo "다음 명령으로 실행하세요: sudo $0"
    exit 1
fi

# .env 파일 로드
if [ -f .env ]; then
    log_info ".env 파일 로드 중..."
    set -a
    source .env
    set +a
fi

HARBOR_HOSTNAME="${HARBOR_HOSTNAME:-192.168.1.100}"
ENABLE_HTTPS="${ENABLE_HTTPS:-false}"
HARBOR_HTTP_PORT="${HARBOR_HTTP_PORT:-80}"
HARBOR_HTTPS_PORT="${HARBOR_HTTPS_PORT:-443}"
CERT_DIR="${CERT_DIR:-./harbor-certs}"

log_info "containerd 설정 시작..."
log_info "Harbor 주소: $HARBOR_HOSTNAME"
log_info "HTTPS 사용: $ENABLE_HTTPS"

# containerd 확인
if ! command -v containerd &> /dev/null; then
    log_error "containerd가 설치되어 있지 않습니다."
    exit 1
fi

# containerd 설정 디렉토리
CONTAINERD_CONFIG_DIR="/etc/containerd"
CONTAINERD_CONFIG="${CONTAINERD_CONFIG_DIR}/config.toml"

# 백업 생성
if [ -f "$CONTAINERD_CONFIG" ]; then
    BACKUP_FILE="${CONTAINERD_CONFIG}.backup.$(date +%Y%m%d%H%M%S)"
    log_info "기존 설정 백업: $BACKUP_FILE"
    cp "$CONTAINERD_CONFIG" "$BACKUP_FILE"
else
    log_info "containerd 설정 파일이 없습니다. 기본 설정 생성 중..."
    mkdir -p "$CONTAINERD_CONFIG_DIR"
    containerd config default > "$CONTAINERD_CONFIG"
fi

# Harbor 레지스트리 주소 결정
if [ "$ENABLE_HTTPS" = "true" ]; then
    if [ "$HARBOR_HTTPS_PORT" != "443" ]; then
        REGISTRY_HOST="${HARBOR_HOSTNAME}:${HARBOR_HTTPS_PORT}"
    else
        REGISTRY_HOST="${HARBOR_HOSTNAME}"
    fi
else
    if [ "$HARBOR_HTTP_PORT" != "80" ]; then
        REGISTRY_HOST="${HARBOR_HOSTNAME}:${HARBOR_HTTP_PORT}"
    else
        REGISTRY_HOST="${HARBOR_HOSTNAME}"
    fi
fi

log_info "레지스트리 주소: $REGISTRY_HOST"

# containerd 설정 업데이트
log_info "containerd 설정 업데이트 중..."

# Python/awk를 사용하여 TOML 파일 수정 (간단한 방법으로 추가)
# registry.configs 섹션에 Harbor 설정 추가

if [ "$ENABLE_HTTPS" = "true" ]; then
    # HTTPS: CA 인증서 설정
    if [ -f "${CERT_DIR}/ca.crt" ]; then
        log_info "HTTPS 모드: CA 인증서 설정"

        # CA 인증서를 시스템 디렉토리에 복사
        CERT_DEST_DIR="/etc/containerd/certs.d/${REGISTRY_HOST}"
        mkdir -p "$CERT_DEST_DIR"
        cp "${CERT_DIR}/ca.crt" "$CERT_DEST_DIR/ca.crt"
        log_info "  CA 인증서 복사: $CERT_DEST_DIR/ca.crt"

        # hosts.toml 생성 (containerd 1.6+)
        cat > "${CERT_DEST_DIR}/hosts.toml" << EOF
# Harbor Registry Configuration
# Generated by configure-containerd.sh

server = "https://${REGISTRY_HOST}"

[host."https://${REGISTRY_HOST}"]
  capabilities = ["pull", "resolve", "push"]
  ca = "${CERT_DEST_DIR}/ca.crt"
  skip_verify = false
EOF
        log_info "  hosts.toml 생성: ${CERT_DEST_DIR}/hosts.toml"
    else
        log_warn "CA 인증서를 찾을 수 없습니다: ${CERT_DIR}/ca.crt"
        log_warn "skip_verify=true로 설정합니다 (보안 경고!)"

        CERT_DEST_DIR="/etc/containerd/certs.d/${REGISTRY_HOST}"
        mkdir -p "$CERT_DEST_DIR"

        cat > "${CERT_DEST_DIR}/hosts.toml" << EOF
# Harbor Registry Configuration (Insecure)
# Generated by configure-containerd.sh

server = "https://${REGISTRY_HOST}"

[host."https://${REGISTRY_HOST}"]
  capabilities = ["pull", "resolve", "push"]
  skip_verify = true
EOF
        log_info "  hosts.toml 생성 (skip_verify): ${CERT_DEST_DIR}/hosts.toml"
    fi
else
    # HTTP: insecure registry 설정
    log_info "HTTP 모드: insecure registry 설정"

    CERT_DEST_DIR="/etc/containerd/certs.d/${REGISTRY_HOST}"
    mkdir -p "$CERT_DEST_DIR"

    cat > "${CERT_DEST_DIR}/hosts.toml" << EOF
# Harbor Registry Configuration (HTTP - Insecure)
# Generated by configure-containerd.sh

server = "http://${REGISTRY_HOST}"

[host."http://${REGISTRY_HOST}"]
  capabilities = ["pull", "resolve", "push"]
  skip_verify = true
EOF
    log_info "  hosts.toml 생성 (HTTP): ${CERT_DEST_DIR}/hosts.toml"
fi

# containerd.service 재시작
log_info "containerd 서비스 재시작 중..."
systemctl daemon-reload
systemctl restart containerd

# 재시작 확인
sleep 3
if systemctl is-active --quiet containerd; then
    log_info "containerd 서비스가 정상적으로 재시작되었습니다."
else
    log_error "containerd 서비스 재시작 실패!"
    log_error "로그 확인: journalctl -u containerd -n 50"
    exit 1
fi

# 설정 확인
log_info ""
log_info "=========================================="
log_info "containerd 설정 완료!"
log_info "=========================================="
log_info "레지스트리: $REGISTRY_HOST"
log_info "설정 디렉토리: $CERT_DEST_DIR"
log_info ""
log_info "테스트 방법:"
log_info "  1. 이미지 pull 테스트:"
log_info "     nerdctl pull ${REGISTRY_HOST}/library/nginx:latest"
log_info ""
log_info "  2. 로그인 테스트:"
log_info "     nerdctl login ${REGISTRY_HOST}"
log_info ""
